version: "3.8"

services:
  postgres-kc:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kc-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-kc-data:/var/lib/postgres/data
    networks:
      - lakilasy-networks

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: root
      KEYCLOAK_ADMIN_PASSWORD: 12345
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-kc
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: 1234
      KC_DB_URL_DATABASE: kc-db
      KC_DB_SCHEMA: public
    command: ["start-dev", "--import-realm"]
    depends_on:
      - postgres-kc
    volumes:
      - kc-data:/opt/jboss/keycloak/standalone/data
    networks:
      - lakilasy-networks

  mongodb-class:
    image: mongo
    container_name: mongodb-class
    ports:
      - "27019:27017"
    expose:
      - "27019"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixml
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: CLASS-DB
    volumes:
      - mongo-class-data:/data/db
    networks:
      - lakilasy-networks

  mongodb-student:
    image: mongo
    container_name: mongodb-student
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixml
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: STUDENT-DB
    volumes:
      - mongo-student-data:/data/db
    networks:
      - lakilasy-networks

  mongodb-professor:
    image: mongo
    container_name: mongodb-professor
    ports:
      - "27018:27017"
    expose:
      - "27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixml
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: PROFESSOR-DB
    volumes:
      - mongo-professor-data:/data/db
    networks:
      - lakilasy-networks

  mongodb-course:
    image: mongo
    container_name: mongodb-course
    ports:
      - "27020:27017"
    expose:
      - "27020"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixml
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: COURSE-DB
    volumes:
      - mongo-course-data:/data/db
    networks:
      - lakilasy-networks

  mongodb-time-table:
    image: mongo
    container_name: mongodb-time-table
    ports:
      - "27021:27017"
    expose:
      - "27021"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixml
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: TIME-TABLE-DB
    volumes:
      - mongo-time-table-data:/data/db
    networks:
      - lakilasy-networks

  mongodb-report-card:
    image: mongo
    container_name: mongodb-report-card
    ports:
      - "27022:27017"
    expose:
      - "27022"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixml
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: COURSE-DB
    volumes:
      - mongo-report-card-data:/data/db
    networks:
      - lakilasy-networks

  mongo-express-class:
    image: mongo-express
    ports:
      - "8083:8081"
    expose:
      - "8083"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ixml
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb-class
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - lakilasy-networks

  mongo-express-student:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ixml
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb-student
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - lakilasy-networks

  mongo-express-professor:
    image: mongo-express
    ports:
      - "8082:8081"
    expose:
      - "8082"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ixml
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb-professor
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - lakilasy-networks

  mongo-express-course:
    image: mongo-express
    ports:
      - "8084:8081"
    expose:
      - "8084"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ixml
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb-course
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - lakilasy-networks

  mongo-express-time-table:
    image: mongo-express
    ports:
      - "8085:8081"
    expose:
      - "8085"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ixml
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb-time-table
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - lakilasy-networks

  mongo-express-report-card:
    image: mongo-express
    ports:
      - "8086:8081"
    expose:
      - "8086"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ixml
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb-report-card
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - lakilasy-networks

networks:
  lakilasy-networks:
    driver: bridge

volumes:
  mongo-class-data:
  mongo-student-data:
  mongo-professor-data:
  mongo-user-data:
  mongo-course-data:
  mongo-time-table-data:
  mongo-report-card-data:
  mongo-property-data:
  postgres-kc-data:
  kc-data:
